#
# Site settings
#

#-
url: https://harbour.pl/howto
baseurl: /howto
title: howto
github_url: https://github.com/rjopek/howto/tree/master/docs

markdown: kramdown
highlighter: rouge

#-
collections:

   bottombordernavlinks:
      output: true
      permalink: /:collection/

   curtainmenu:
      output: true
      permalink: /:collection/

   equalwidthnavbar:
      output: true
      permalink: /:collection/

   mobilehorizontalmenu:
      output: true
      permalink: /:collection/

   mobileverticalmenu:
      output: true
      permalink: /:collection/

   off-canvasmenu:
      output: true
      permalink: /:collection/

   responsivetopnavigation:
      output: true
      permalink: /:collection/

   tabheaders:
      output: true
      permalink: /:collection/

   topnavigation:
      output: true
      permalink: /:collection/

   verticalmenu:
      output: true
      permalink: /:collection/

   verticalslidingmenu:
      output: true
      permalink: /:collection/
