#
# Site settings
#

#-
url: https://harbour.pl/howto
baseurl: /howto
title: howto
github_url: https://github.com/rjopek/howto/tree/master/docs

markdown: kramdown
highlighter: rouge

#-
collections:

   mobilehorizontalmenu:
      output: true
      permalink: /:collection/

   mobileverticalmenu:
      output: true
      permalink: /:collection/

   verticalmenu:
      output: true
      permalink: /:collection/

   verticalslidingmenu:
      output: true
      permalink: /:collection/
